version: "3.7"

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    hostname: mysql-master
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"       
    command: >
      mysqld
        --server-id=1
        --log-bin=mysql-bin
        --binlog-format=ROW
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/initdb:/docker-entrypoint-initdb.d
      - ./master/conf.d:/etc/mysql/conf.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    hostname: mysql-slave
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    command: >
      mysqld
        --server-id=2
        --log-bin=mysql-bin
        --binlog-format=ROW
        --relay-log=relay-bin
    depends_on:
      - mysql-master
    volumes:
      - ./slave/data:/var/lib/mysql
      - ./slave/initdb:/docker-entrypoint-initdb.d
      - ./slave/conf.d:/etc/mysql/conf.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5